### ISSUE TITLE
Speedup testing process [tutorials]

### ISSUE THREAD

**Issue by wei-enwang** [sibyl-dev/pyreal#429] opened 2023-07-10 02:21 UTC
`tutorials/custom_transformers.ipynb` takes a while to run (~30 seconds). While not a major issue at all, would be nice to deal with it since it runs every time we start a test session.

**Comment by zyteka** [comment] 2023-07-10 13:58
Duplicate of #368, updated that issue with the additional details from here (and adding to at-bat)

**Closed as completed by zyteka** 2023-07-10 13:58 UTC
Labels: enhancement
